# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
# Modified by Authors of "Towards ML-KEM & ML-DSA on OpenTitan" (https://eprint.iacr.org/2024/1192).
# Copyright "Towards ML-KEM & ML-DSA on OpenTitan" Authors.


load("//rules:otbn.bzl", "otbn_consttime_test", "otbn_library", "otbn_sim_test", "otbn_sim_py_test", "otbn_binary")

package(default_visibility = ["//visibility:public"])


otbn_binary(
    name = "bnaddv_test",
    srcs = [
        "bnaddv_test.s",
    ],
)

otbn_binary(
    name = "bnaddvm_test",
    srcs = [
        "bnaddvm_test.s",
    ],
)

otbn_binary(
    name = "bnmulv_test",
    srcs = [
        "bnmulv_test.s",
    ],
)

otbn_binary(
    name = "bnmulvl_test",
    srcs = [
        "bnmulvl_test.s",
    ],
)

otbn_binary(
    name = "bnmulvm_test",
    srcs = [
        "bnmulvm_test.s",
    ],
)

otbn_binary(
    name = "bnmulvml_test",
    srcs = [
        "bnmulvml_test.s",
    ],
)

otbn_binary(
    name = "bnshv_test",
    srcs = [
        "bnshv_test.s",
    ],
)

otbn_binary(
    name = "bntrn_test",
    srcs = [
        "bntrn_test.s",
    ],
)